### ISSUE TITLE
Fails to detect changes done by other plugins

### ISSUE THREAD

**Issue by fama** [woolfg/dokuwiki-plugin-gitbacked#51] opened 2020-09-21 23:27 UTC
We have two plugins that gitabacked fails to detect:

- [Draw.io plugin](https://www.dokuwiki.org/plugin:drawio):  The plugin will create a .png file in the media folder.  But gitbacked does not detect the new file and thus it's not added to the git repo.
- [Move Plugin](https://www.dokuwiki.org/plugin:move):  The new location of the files is not detected by gitbacked and thus also does not get backed up.

I think the solution may be to periodically add all files in the `pages` and `media` folders.  Similarly as doing periodic `git pull` if enabled in the configuration.

**Comment by woolfg** [comment] 2020-09-23 20:05
I guess there are two options:

- implement all hooks that are missing to track all changes of other plugins (this depends on the plugins and the plugins have to call hooks)
- a periodic commit which is imho not that clean as it could lead to non intended behaviour

@fama, do you have any information about the plugins if the call any hooks when creating files? I think this would be the clean solution. Plugins should call hooks and other plugins can react to it.

**Comment by fama** [comment] 2020-09-24 19:20
I looked at the code and with my very limited php experience, it seems:

1. [draw.io action.php](https://github.com/lejmr/dokuwiki-plugin-drawio/blob/master/action.php) does not create any suitable event
2. [dokuwiki-plugin-move's op.php](https://github.com/michitux/dokuwiki-plugin-move/blob/master/helper/op.php) seems to use an event `PLUGIN_MOVE_MEDIA_RENAME`.  Not sure if this is helpful.

I do like the periodic add/commit solution because:

1. Config already specifies in which paths to ignore `plugin»gitbacked»ignorePaths`.  All the other newly created pages and media files get backed up upon creation/update anyway. 
2. There may be other plugins now or in the future that my not be firing events and thus running into the same risk of missing backup.
3. There already is a similar functionality with `plugin»gitbacked»periodicPull`.  Maybe a `plugin»gitbacked»periodicAddCommit` as an option may be helpful to prevent missing backups.

**Comment by woolfg** [comment] 2020-10-08 09:59
I see, maybe as an optional feature it could solve some issues, true. @fama, would you be up to develop this feature and send a Pull Request? It would help the project and the community a lot. I can also give some guidance when needed.

**Comment by ochurlaud** [comment] 2022-02-07 22:10
at least we should find this one https://github.com/woolfg/dokuwiki-plugin-gitbacked/commit/8457ba7e9b7c6f553a9c104f91ea1d6cb48a5c13

**Comment by woolfg** [comment] 2023-01-25 17:50
hey @annProg, thanks for the input. I think it would help multiple people. do you want to implement it?

**Comment by annProg** [comment] 2023-01-26 16:23
> hey @annProg, thanks for the input. I think it would help multiple people. do you want to implement it?

I have implemented periodic pushes with crontab, and it works quite well, maybe there is no need to implement it in the plugin

**Comment by woolfg** [comment] 2023-04-18 22:12
also a good solution @annProg , especially a pragmatic one. I will close the issue for now, but can be reopened at any time.

**Closed by woolfg** 2023-04-18 22:12 UTC
Labels: feature request
